baseURL = "https://enzottic.me/"
theme = "hugo-theme-console"
languageCode = "en-us"
title = "enzo"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "photos"
  url = "photos/"

  [[params.navlinks]]
  name = "projects"
  url = "projects/"

[markup.goldmark.renderer]
unsafe = true
  
